### PR TITLE
Refactor sync() method, closes #11

### LINKED ISSUE #11: Refactor sync() method in IInteractions to be visible and fully functional
### Is your feature request related to a problem? Please describe.
Currently only the `syncOnReady()` method is exposed in `IInteractions`. This means that any projects that need to wait for the client to be ready, do some processing and then sync slash commands cannot do so.

### Describe the solution you'd like 
Expose the `sync()` method in `IInteractions`. 

### Describe alternatives you've considered
It is possible to directly import `package:nyxx_interactions/src/interactions.dart` however this is against dart style guides and package guidelines.

### PR DESCRIPTION
**Pull request by abitofevrything**
Would like to discuss the motivation behind moving the subscription to event streams out of `sync()` to `syncOnReady()` before merging this.

### CODE REVIEW

**Review by l7ssha — APPROVED** [review]
Right now I can't tell why it was moved. It was druring refactoring of these methods to better handle registering of commands. Are examples working after your changes - if so I think its good to merge :)

**Comment by abitofevrything** [comment]
Examples are working apart from buttons & dropdowns example, however the errors there don't seem to be due to this change, and fixing the various errors in the example do make it work correctly.

**Comment by l7ssha** [comment]
> Examples are working apart from buttons & dropdowns example, however the errors there don't seem to be due to this change, and fixing the various errors in the example do make it work correctly.

Aight then, can you push fixes for examples? We'll be good to merge afterwards

**Comment by abitofevrything** [comment]
The fixes I applied are just temporary hacks and I'm not sure where the underlying problem lies...

I think opening a separate issue for this would be more appropriate, but here are the two problems for reference:
- attempting to send a `MessageBuilder` with no content causes an error
- the action row exceeds the maximum width

**Comment by l7ssha** [comment]
All right then, merging it. Thanks for contribution :)

**Pull request merged**
